"""new fields in user model

Revision ID: 66306e795115
Revises: 9c9d32da75cd
Create Date: 2018-05-14 17:27:06.313119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66306e795115'
down_revision = '9c9d32da75cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
